import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image';

import Banner from '../components/Banner';
import Card from '../components/Card';

import coffeeStoresData from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  console.log("hi getStaticProps")

  const options = {
    method: 'GET',
    headers: {
      accept: 'application/json',
      Authorization: 'fsq3iZaspGD6tnr++djD9LXNFyZtFwMChDu2KkohBnMX4NI='
    }
  };
  
  const response = await fetch('https://api.foursquare.com/v3/places/search?query=coffee&ll=39.53296611001593%2C-0.41184749150409933&limit=6', options);
  const data = await response.json();
  
    // .catch(err => console.error(err));

  return {
    props: {
      coffeeStores: data.results,
    }
  }
}
 
export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} alt=''/>
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(coffeeStore => {
                return (
                  <Card 
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"}
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>)}
      </main>
    </div>
  )
}  
